services:
  web:
    #image: flaskapp
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    ports:
      - "5000:8080"
    environment:
      MYSQL_PASSWORD: testapppass
      MYSQL_USER: testappuser
      MYSQL_HOST: db
      REDIS_HOST: redis
      DB_NAME: mydatabase
  redis:
    image: "redis:alpine"
  db:
    image: mysql:8.4.0-oraclelinux8
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: testapproot
      MYSQL_USER: testappuser
      MYSQL_PASSWORD: testapppass
      MYSQL_DATABASE: mydatabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 0s