name: Deploy Helm Chart to EKS

on:
  push:
    paths:
      - 'incode/helm/testapp/**'
      - '.github/workflows/deploy-helm-chart.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name devopsbg

      - name: Deploy Helm chart
        run: |
          cd incode/helm/testapp
          helm lint .
          helm -n testapp upgrade --install testapp . --atomic --reuse-values
